Repository microsoft/playwright, pull requests merged in 2021-05, with the labels that each got.

#6518 devops: run less tests on each PR
  .github/workflows/tests_chrome_beta.yml
  .github/workflows/tests_primary.yml
  .github/workflows/tests_secondary.yml
Labels: CQ1

#6522 chore(test): fix some screencast tests
  src/server/firefox/ffPage.ts
  src/server/webkit/wkPage.ts
  tests/tracing.spec.ts
Labels: CQ1

#6523 chore(tracing): expose tracing api
  docs/src/api/class-browsercontext.md
  docs/src/api/class-tracing.md
  src/cli/cli.ts
  src/client/api.ts
  src/client/browserContext.ts
  src/client/tracing.ts
  src/protocol/channels.ts
  src/protocol/protocol.yml
  src/protocol/validator.ts
  src/server/browserType.ts
  src/server/snapshot/snapshotServer.ts
  src/server/trace/viewer/traceViewer.ts
  src/server/types.ts
  tests/config/browserTest.ts
  tests/config/default.config.ts
  tests/snapshotter.spec.ts
  tests/tracing.spec.ts
  types/types.d.ts
Labels: CQ1

#6541 fix(CR): handle backgroundPages() onClose
  src/client/page.ts
  tests/chromium/launcher.spec.ts
Labels: CQ1

#6550 feat(webkit): bump to 1478
  browsers.json
Labels: CQ1

#6370 feat(network): expose network events via browser context
  docs/src/api/class-browsercontext.md
  src/client/browserContext.ts
  src/client/events.ts
  src/client/page.ts
  src/dispatchers/browserContextDispatcher.ts
  src/dispatchers/pageDispatcher.ts
  src/protocol/channels.ts
  src/protocol/protocol.yml
  src/server/browserContext.ts
  src/server/chromium/crNetworkManager.ts
  src/server/frames.ts
  src/server/page.ts
  tests/browsercontext-network-event.spec.ts
  tests/channels.spec.ts
  types/types.d.ts
Labels: CQ1

#6561 feat(firefox): roll to latest Firefoxes
  browsers.json
  src/server/firefox/protocol.ts
  tests/page/page-set-input-files.spec.ts
Labels: CQ1

#6511 fix(chromium): wait for existing pages when connecting
  src/client/electron.ts
  src/server/chromium/crBrowser.ts
  src/server/electron/electron.ts
  tests/chromium/chromium.spec.ts
  tests/electron/electron-app.spec.ts
Labels: CQ1, v1.11.1

#6562 fix(har): save popup's main request/response
  src/server/frames.ts
  src/server/page.ts
  src/server/snapshot/snapshotter.ts
  src/server/supplements/har/harTracer.ts
  tests/har.spec.ts
Labels: CQ1

#6586 test(downloads): add passing test for downloads and interception
  tests/download.spec.ts
Labels: CQ1

#6570 test: roll to folio@0.4.0-alpha13
  package-lock.json
  package.json
  tests/browsercontext-device.spec.ts
  tests/browsercontext-proxy.spec.ts
  tests/chromium/oopif.spec.ts
  tests/config/android.config.ts
  tests/config/baseTest.ts
  tests/config/browserTest.ts
  tests/config/default.config.ts
  tests/config/electron.config.ts
  tests/config/remoteServer.ts
  tests/inspector/inspectorTest.ts
  tests/tap.spec.ts
Labels: CQ1

#6588 test: enable download url test on webkit
  tests/download.spec.ts
Labels: CQ1

#6602 test: roll to folio@0.4.0-alpha14
  package-lock.json
  package.json
  tests/android/androidTest.ts
  tests/browsercontext-proxy.spec.ts
  tests/chromium/oopif.spec.ts
  tests/config/android.config.ts
  tests/config/baseTest.ts
  tests/config/browserTest.ts
  tests/config/default.config.ts
  tests/config/electron.config.ts
  tests/electron/electronTest.ts
  tests/inspector/inspectorTest.ts
  tests/page/page-event-crash.spec.ts
  tests/page/pageTest.ts
  tests/snapshotter.spec.ts
  tests/tap.spec.ts
  tests/tracing.spec.ts
Labels: CQ1

#6605 feat(webkit): bump to 1480
  browsers.json
  src/server/webkit/protocol.ts
Labels: CQ1

#6616 fix(tests): force a new worker for channels.spec
  tests/channels.spec.ts
Labels: CQ1

#6609 test: unskip a few tests previously skipped with channels
  tests/browsertype-launch-server.spec.ts
  tests/chromium/launcher.spec.ts
  tests/headful.spec.ts
  tests/signals.spec.ts
Labels: CQ1

#6594 feat: use up2date Chromium user-agents for device descriptors
  packages/common/.npmignore
  src/server/deviceDescriptors.js
  src/server/deviceDescriptorsSource.json
  tests/inspector/cli-codegen-java.spec.ts
  tsconfig.json
  utils/doclint/cli.js
Labels: CQ1

#6608 fix(chromium): close background pages on close
  src/server/browserContext.ts
  src/server/chromium/crBrowser.ts
  src/server/firefox/ffBrowser.ts
  src/server/webkit/wkBrowser.ts
  tests/chromium/launcher.spec.ts
Labels: CQ1

#6187 fix(codegen): move injected recorder scripts to utility world
  src/dispatchers/browserContextDispatcher.ts
  src/server/browserContext.ts
  src/server/frames.ts
  src/server/supplements/recorderSupplement.ts
  src/server/trace/viewer/traceViewer.ts
Labels: CQ1

#6635 feat(chromium): roll Chromium to r879910
  README.md
  browsers.json
  src/server/deviceDescriptorsSource.json
Labels: CQ1

#6648 fix: wait for ffmpeg to finish writing even if page was closed
  src/server/chromium/crPage.ts
  tests/video.spec.ts
Labels: v1.11.1

#6621 feat(electron): accept BrowserContextOptions in electron.launch
  docs/src/api/class-electron.md
  src/client/electron.ts
  src/protocol/channels.ts
  src/protocol/protocol.yml
  src/protocol/validator.ts
  src/server/electron/electron.ts
  tests/electron/electron-app.spec.ts
  types/types.d.ts
Labels: CQ1

#6652 feat(webkit): bump to 1481
  browsers.json
Labels: CQ1

#6676 feat(webkit): roll to 1482
  browsers.json
  src/server/webkit/protocol.ts
Labels: CQ1

#6678 feat(firefox): roll to 1265
  browsers.json
  src/server/firefox/protocol.ts
Labels: CQ1

#6656 test: roll to folio@0.4.0-alpha16
  package-lock.json
  package.json
  tests/__snapshots__/screenshot/should-work-with-a-mobile-viewport-and-clip/chromium/screenshot-mobile-clip.png
  tests/android/androidTest.ts
  tests/browsercontext-pages.spec.ts
  tests/browsertype-connect.spec.ts
  tests/config/android.config.ts
  tests/config/baseTest.ts
  tests/config/browserTest.ts
  tests/config/default.config.ts
  tests/config/electron.config.ts
  tests/defaultbrowsercontext-1.spec.ts
  tests/page/page-drag.spec.ts
  tests/proxy.spec.ts
  tests/screenshot.spec.ts
  tests/signals.spec.ts
Labels: CQ1

#6685 fix(codegen): update csharp scripts to new syntax
  src/server/supplements/injected/recorder.ts
  src/server/supplements/recorder/csharp.ts
  src/server/supplements/recorder/recorderActions.ts
  src/server/supplements/recorderSupplement.ts
  tests/inspector/cli-codegen-1.spec.ts
  tests/inspector/cli-codegen-2.spec.ts
  tests/inspector/cli-codegen-csharp.spec.ts
Labels: CQ1

#6686 feat(chromium): roll Chromium to r884693
  README.md
  browsers.json
  src/server/chromium/protocol.ts
  src/server/deviceDescriptorsSource.json
  types/protocol.d.ts
Labels: CQ1

#6697 fix(codegen): generate acceptDownloads option for download signals
  src/cli/cli.ts
  src/server/supplements/recorder/codeGenerator.ts
  tests/inspector/cli-codegen-2.spec.ts
Labels: CQ1

#6698 fix(codegen): generate all options for java
  src/cli/cli.ts
  src/server/supplements/recorder/java.ts
  tests/inspector/cli-codegen-1.spec.ts
  tests/inspector/cli-codegen-2.spec.ts
  tests/inspector/cli-codegen-java.spec.ts
Labels: CQ1

#6646 feat: added reduced motion media query emulation
  browsers.json
  docs/src/api/class-page.md
  docs/src/api/params.md
  src/client/page.ts
  src/dispatchers/pageDispatcher.ts
  src/protocol/channels.ts
  src/protocol/protocol.yml
  src/protocol/validator.ts
  src/server/chromium/crPage.ts
  src/server/firefox/ffBrowser.ts
  src/server/firefox/ffPage.ts
  src/server/page.ts
  src/server/types.ts
  src/server/webkit/wkPage.ts
  tests/defaultbrowsercontext-2.spec.ts
  tests/page/page-emulate-media.spec.ts
  types/types.d.ts
Labels: CQ1

#6712 test: roll to folio@0.4.0-alpha17
  package-lock.json
  package.json
  tests/inspector/inspectorTest.ts
  tests/snapshotter.spec.ts
Labels: CQ1

#6742 fix(codegen): update csharp boilerplate
  src/server/supplements/recorder/csharp.ts
  tests/inspector/cli-codegen-csharp.spec.ts
Labels: CQ1

#6735 feat: do not rely on chocolatey to install Google Chrome Beta
  .github/workflows/tests_secondary.yml
  utils/install-chrome-beta/reinstall_win.ps1
Labels: CQ1

#6745 fix(port-forwarding): on WebKit Win
  src/utils/utils.ts
  tests/portForwardingServer.spec.ts
Labels: CQ1

#6762 fix(connect): respect timeout in all scenarios
  src/client/browserType.ts
  tests/browsertype-connect.spec.ts
  tests/capabilities.spec.ts
  tests/chromium/chromium.spec.ts
  tests/ignorehttpserrors.spec.ts
  tests/web-socket.spec.ts
  utils/testserver/index.d.ts
  utils/testserver/index.js
Labels: CQ1

#6604 fix(inspector): do not pause while recording
  src/server/supplements/debugger.ts
  src/server/supplements/recorderSupplement.ts
Labels: CQ1

#6774 test: roll to folio@0.4.0-alpha19
  package-lock.json
  package.json
Labels: CQ1

#6779 feat(firefox): bump to 1268
  README.md
  browsers.json
  tests/page/page-evaluate.spec.ts
Labels: CQ1

#6741 feat(webkit): bump to 1486
  browsers.json
Labels: CQ1
