Repository microsoft/playwright, pull requests merged in 2021-08, with the labels that each got.

#7951 feat(inputValue): implement inputValue for select elements
  docs/src/api/class-elementhandle.md
  docs/src/api/class-frame.md
  docs/src/api/class-locator.md
  docs/src/api/class-page.md
  src/server/common/domErrors.ts
  src/server/dom.ts
  tests/assets/dom.html
  tests/page/elementhandle-convenience.spec.ts
  tests/page/locator-convenience.spec.ts
  types/types.d.ts
Labels: CQ1

#7975 test: fulfilled intercepted response body
  tests/page/page-request-intercept.spec.ts
Labels: CQ1

#7974 feat(tracing): introduce _reset() and _export()
  src/client/tracing.ts
  src/dispatchers/browserContextDispatcher.ts
  src/protocol/channels.ts
  src/protocol/protocol.yml
  src/protocol/validator.ts
  src/server/snapshot/snapshotter.ts
  src/server/trace/common/traceEvents.ts
  src/server/trace/recorder/traceSnapshotter.ts
  src/server/trace/recorder/tracing.ts
  tests/tracing.spec.ts
Labels: CQ1

#7977 chore: roll test runner to ToT
  tests/config/test-runner/package-lock.json
  tests/config/test-runner/package.json
Labels: CQ1

#7985 test: fix locator-misc-1 tests on Android
  tests/page/locator-misc-1.spec.ts
  tests/tap.spec.ts
Labels: CQ1, android

#7988 test: use os-specific EOL sequence in test expectaions
  tests/page/page-request-intercept.spec.ts
Labels: CQ1

#7986 feat(firefox-beta): roll to 1273
  browsers.json
Labels: CQ1

#7992 feat(tracing): allow calling tracing.start multiple times
  src/client/tracing.ts
  src/dispatchers/browserContextDispatcher.ts
  src/protocol/channels.ts
  src/protocol/protocol.yml
  src/protocol/validator.ts
  src/server/snapshot/inMemorySnapshotter.ts
  src/server/snapshot/snapshotterInjected.ts
  src/server/trace/recorder/tracing.ts
  tests/snapshotter.spec.ts
  tests/tracing.spec.ts
Labels: CQ1

#7910 feat: response interception after redirects in chromium
  src/server/chromium/crNetworkManager.ts
  src/server/firefox/ffNetworkManager.ts
  src/server/frames.ts
  src/server/network.ts
  src/server/page.ts
  src/server/webkit/wkInterceptableRequest.ts
  src/server/webkit/wkPage.ts
  tests/page/page-request-intercept.spec.ts
Labels: CQ1

#8020 fix(trace viewer): render snapshots with correct viewport size
  src/server/snapshot/snapshotterInjected.ts
  src/server/trace/recorder/tracing.ts
  src/server/trace/viewer/traceModel.ts
  src/web/traceViewer/ui/callTab.tsx
  src/web/traceViewer/ui/snapshotTab.tsx
  src/web/traceViewer/ui/workbench.tsx
  tests/trace-viewer/trace-viewer.spec.ts
Labels: CQ1

#8025 chore: roll test runner to ToT
  tests/config/test-runner/package-lock.json
  tests/config/test-runner/package.json
Labels: CQ1

#8063 chore: roll test runner to ToT
  tests/config/test-runner/package-lock.json
  tests/config/test-runner/package.json
Labels: CQ1

#7194 devops: support `npx playwright install --with-deps` command
  .github/workflows/tests_fyi.yml
  .github/workflows/tests_primary.yml
  .github/workflows/tests_secondary.yml
  src/cli/cli.ts
Labels: CQ1

#8065 feat(ff-beta): roll ff-beta to 1274
  browsers.json
Labels: CQ1

#8047 feat(chromium): roll Chromium to M94
  README.md
  browsers.json
  src/server/chromium/chromium.ts
  src/server/chromium/crBrowser.ts
  src/server/chromium/protocol.d.ts
  src/server/deviceDescriptorsSource.json
  tests/browsercontext-add-cookies.spec.ts
  tests/browsercontext-cookies.spec.ts
  tests/browsercontext-route.spec.ts
  tests/defaultbrowsercontext-1.spec.ts
  tests/headful.spec.ts
  types/protocol.d.ts
Labels: CQ1

#8083 fix(test runner): make sure options, trace and screenshot apply to all contexts
  src/client/browser.ts
  src/client/browserContext.ts
  src/client/browserType.ts
  src/client/channelOwner.ts
  src/client/page.ts
  src/test/index.ts
  tests/playwright-test/golden.spec.ts
  tests/playwright-test/playwright.artifacts.spec.ts
  tests/playwright-test/playwright.spec.ts
  tests/playwright-test/reporter.spec.ts
  tests/playwright-test/retry.spec.ts
  tests/playwright-test/test-output-dir.spec.ts
  types/test.d.ts
  utils/generate_types/overrides-test.d.ts
Labels: CQ1

#8112 fix(tests): do not throw if page did not produce video
  tests/config/browserTest.ts
Labels: CQ1

#8138 test: update sameSite cookie expectations on WebKit Win
  tests/browsercontext-add-cookies.spec.ts
  tests/browsercontext-cookies.spec.ts
  tests/defaultbrowsercontext-1.spec.ts
Labels: CQ1

#8017 feat(webkit): response interception after redirects
  src/server/webkit/wkInterceptableRequest.ts
  tests/page/page-request-intercept.spec.ts
Labels: CQ1

#8148 feat(firefox): response interception after redirects
  tests/page/page-request-intercept.spec.ts
Labels: CQ1

#8151 fix: fulfill intercepted response with empty body
  src/client/network.ts
  src/server/firefox/ffNetworkManager.ts
  src/server/network.ts
  tests/page/page-request-intercept.spec.ts
Labels: CQ1

#8154 chore: bump ff beta to 1275
  browsers.json
Labels: CQ1

#8162 fix: do not show the "accept incoming network connections" dialog
  src/server/chromium/chromium.ts
Labels: CQ1

#8167 test: download event for navigations that change into downloads
  tests/download.spec.ts
Labels: CQ1

#8169 test: fix electron tests
  tests/page/page-request-intercept.spec.ts
Labels: CQ1

#8166 fix(firefox): fulfill response with empty body
  browsers.json
  tests/page/page-request-intercept.spec.ts
Labels: CQ1

#8172 feat(webkit): bump to 1531
  browsers.json
Labels: CQ1

#8209 fix(android): fix android tests
  tests/android/androidTest.ts
  tests/android/browser.spec.ts
  utils/avd_install.sh
  utils/avd_recreate.sh
  utils/avd_start.sh
Labels: CQ1

#8157 api(cdp): newCDPSession accepts frames, too
  docs/src/api/class-browsercontext.md
  src/client/browserContext.ts
  src/dispatchers/browserContextDispatcher.ts
  src/protocol/channels.ts
  src/protocol/protocol.yml
  src/protocol/validator.ts
  src/server/chromium/crBrowser.ts
  tests/chromium/oopif.spec.ts
  tests/chromium/session.spec.ts
  types/types.d.ts
Labels: CQ1

#8228 chore: bump ff beta to 1278
  browsers.json
Labels: CQ1

#8195 fix: throw if intercepted response fails
  browsers.json
  src/server/chromium/crNetworkManager.ts
  src/server/firefox/protocol.d.ts
  src/server/webkit/wkInterceptableRequest.ts
  src/server/webkit/wkPage.ts
  tests/page/page-request-intercept.spec.ts
Labels: CQ1

#8236 fix(tracing): improve captureStackTrace
  src/utils/stackTrace.ts
  src/web/traceViewer/ui/stackTrace.tsx
  tests/trace-viewer/trace-viewer.spec.ts
Labels: CQ1

#8262 fix(expect): highlight diff in toHaveText
  src/test/matchers/toMatchText.ts
Labels: v1.14

#8267 feat(codegen): support --save-trace option
  src/cli/cli.ts
  src/server/supplements/recorderSupplement.ts
  tests/inspector/cli-codegen-2.spec.ts
Labels: CQ1

#8291 chore: roll test runner to ToT
  tests/config/test-runner/package-lock.json
  tests/config/test-runner/package.json
Labels: CQ1

#8296 fix(tracing): serialize resource writes against trace export
  src/server/trace/recorder/traceSnapshotter.ts
  src/server/trace/recorder/tracing.ts
  tests/tracing.spec.ts
Labels: CQ1

#8299 test: proxy server fixture, new test for https via http proxy
  package-lock.json
  package.json
  tests/browsercontext-proxy.spec.ts
  tests/config/baseTest.ts
  tests/config/proxy.ts
Labels: CQ1

#8240 test: skip interception test in electron
  tests/page/page-request-intercept.spec.ts
Labels: CQ1

#8019 chore(protocol): do client hello instead of server hello
  src/browserServerImpl.ts
  src/cli/driver.ts
  src/client/browserType.ts
  src/client/connection.ts
  src/client/playwright.ts
  src/dispatchers/dispatcher.ts
  src/inprocess.ts
  src/outofprocess.ts
  src/protocol/channels.ts
  src/protocol/protocol.yml
  src/protocol/validator.ts
  src/remote/playwrightClient.ts
  src/remote/playwrightServer.ts
  tests/browsertype-connect.spec.ts
Labels: CQ1

#8314 fix(types): toHaveAttribute had its signature backwards
  types/testExpect.d.ts
Labels: v1.14

#8315 chore: reimplement socks to be readable
  src/browserServerImpl.ts
  src/cli/cli.ts
  src/cli/driver.ts
  src/client/browserType.ts
  src/client/connection.ts
  src/client/playwright.ts
  src/client/socksSocket.ts
  src/client/types.ts
  src/dispatchers/playwrightDispatcher.ts
  src/dispatchers/socksSocketDispatcher.ts
  src/protocol/channels.ts
  src/protocol/protocol.yml
  src/protocol/validator.ts
  src/remote/playwrightClient.ts
  src/remote/playwrightServer.ts
  src/server/browser.ts
  src/server/browserType.ts
  src/server/chromium/chromium.ts
  src/server/playwright.ts
  src/server/socksServer.ts
  src/server/socksSocket.ts
  src/utils/netUtils.ts
  src/utils/socksProxy.ts
  tests/port-forwarding-server.spec.ts
  tests/portForwardingServer.spec.ts
Labels: CQ1

#8316 test: add a tracing bot that collects a trace for most contexts
  .github/workflows/tests_secondary.yml
  src/client/browserContext.ts
  tests/chromium/js-coverage.spec.ts
  tests/config/baseTest.ts
  tests/config/browserTest.ts
  tests/config/default.config.ts
  tests/config/remoteServer.ts
  tests/page/page-dialog.spec.ts
  tests/tracing.spec.ts
Labels: CQ1

#8378 chore(tracing): rework start/export chunks
  src/server/trace/common/traceEvents.ts
  src/server/trace/recorder/tracing.ts
  src/server/trace/viewer/traceViewer.ts
  tests/tracing.spec.ts
Labels: CQ1

#8383 fix(test): fix broken codegen test
  tests/inspector/cli-codegen-2.spec.ts
  tests/inspector/cli-codegen-csharp.spec.ts
  tests/inspector/cli-codegen-java.spec.ts
  tests/inspector/cli-codegen-javascript.spec.ts
  tests/inspector/cli-codegen-python-async.spec.ts
  tests/inspector/cli-codegen-python.spec.ts
  tests/inspector/cli-codegen-test.spec.ts
  tests/inspector/inspectorTest.ts
Labels: CQ1

#8386 feat(route): rename method, add response option
  docs/src/api/class-route.md
  src/client/network.ts
  src/protocol/channels.ts
  src/protocol/protocol.yml
  src/protocol/validator.ts
  src/server/network.ts
  tests/page/page-request-intercept.spec.ts
  types/types.d.ts
Labels: CQ1

#8391 chore: migrate tracing ResourceSnapshot to follow har entry format
  src/server/snapshot/snapshotRenderer.ts
  src/server/snapshot/snapshotServer.ts
  src/server/snapshot/snapshotTypes.ts
  src/server/snapshot/snapshotter.ts
  src/server/supplements/har/har.ts
  src/server/supplements/har/harTracer.ts
  src/server/trace/recorder/tracing.ts
  src/utils/httpServer.ts
  src/web/traceViewer/ui/modelUtil.ts
  src/web/traceViewer/ui/networkResourceDetails.tsx
  tests/snapshotter.spec.ts
  tests/tracing.spec.ts
Labels: CQ1

#8415 fix(codegen): properly escape everything for windows
  src/server/supplements/recorder/java.ts
  src/server/supplements/recorder/javascript.ts
  src/server/supplements/recorder/python.ts
Labels: CQ1

#8349 feat: introduce BrowserContext._fetch
  package-lock.json
  package.json
  src/client/browserContext.ts
  src/client/network.ts
  src/dispatchers/browserContextDispatcher.ts
  src/protocol/channels.ts
  src/protocol/protocol.yml
  src/protocol/validator.ts
  src/server/fetch.ts
  src/server/types.ts
  tests/browsercontext-fetch.spec.ts
Labels: CQ1

#8419 test: override dns lookup to support subdomains
  tests/browsercontext-fetch.spec.ts
Labels: CQ1

#8425 fix(fetch): skip tests on non-default modes, add node-fetch to deps list
  packages/build_package.js
  tests/browsercontext-fetch.spec.ts
Labels: CQ1

#8417 chore: migrate tracing to har
  src/server/browserContext.ts
  src/server/snapshot/inMemorySnapshotter.ts
  src/server/snapshot/snapshotTypes.ts
  src/server/snapshot/snapshotter.ts
  src/server/supplements/har/harRecorder.ts
  src/server/supplements/har/harTracer.ts
  src/server/trace/recorder/tracing.ts
  tests/har.spec.ts
Labels: CQ1

#8430 test: fix package installation tests
  src/server/supplements/recorder/recorderApp.ts
  tests/config/baseTest.ts
Labels: CQ1

#8518 test: fix failing HAR tests due request has not been finished
  tests/har.spec.ts
  tests/page/page-network-request.spec.ts
Labels: CQ1

#8523 test: roll test runner to aug-27
  tests/config/test-runner/package-lock.json
  tests/config/test-runner/package.json
Labels: CQ1

#8526 fix(cookies): read response headers off extra info event, if any
  src/client/browserContext.ts
  src/client/network.ts
  src/dispatchers/browserContextDispatcher.ts
  src/protocol/channels.ts
  src/protocol/protocol.yml
  src/protocol/validator.ts
  src/server/chromium/crNetworkManager.ts
  src/server/firefox/ffNetworkManager.ts
  src/server/frames.ts
  src/server/network.ts
  src/server/supplements/har/harTracer.ts
  src/server/webkit/wkPage.ts
  src/utils/utils.ts
  tests/page/page-network-request.spec.ts
  utils/testserver/index.d.ts
  utils/testserver/index.js
Labels: CQ1

#8559 test: fix webkit win expectation for sameSite attribute
  tests/browsercontext-fetch.spec.ts
Labels: CQ1

#8560 chore: simplify responseExtraInfo handling
  src/server/chromium/crNetworkManager.ts
Labels: CQ1

#8565 fix(fetch): throw on network error
  src/server/fetch.ts
  tests/browsercontext-fetch.spec.ts
Labels: CQ1

#8569 fix(network): extra info can arrive before will send request
  src/client/browserContext.ts
  src/client/network.ts
  src/dispatchers/networkDispatchers.ts
  src/protocol/channels.ts
  src/protocol/protocol.yml
  src/protocol/validator.ts
  src/server/chromium/crNetworkManager.ts
  src/server/firefox/ffNetworkManager.ts
  src/server/frames.ts
  src/server/network.ts
  src/server/webkit/wkPage.ts
Labels: CQ1

#8558 devops: try running Android tests on MacOS 11
  .github/workflows/tests_fyi.yml
Labels: CQ1

#8566 chore: implement browserType.connect on the driver side
  src/client/browserType.ts
  src/client/connection.ts
  src/client/jsonPipe.ts
  src/dispatchers/browserTypeDispatcher.ts
  src/dispatchers/dispatcher.ts
  src/dispatchers/jsonPipeDispatcher.ts
  src/dispatchers/pageDispatcher.ts
  src/dispatchers/streamDispatcher.ts
  src/protocol/channels.ts
  src/protocol/protocol.yml
  src/protocol/validator.ts
  tests/browsertype-launch-server.spec.ts
Labels: CQ1
